### ISSUE TITLE
Possible issue - Psi parameter seems to be getting set wrong

### ISSUE THREAD

**Issue by a-urq** [citylikeamradio/ecape-py#2]
This library's computation contains a 4 coefficient multiplying all terms in the denominator.
```python
@check_units("[length]")
def calc_psi(el_z: pint.Quantity) -> pint.Quantity:
    """
    Calculate the constant psi as denoted in eqn. 52

    Args:
        el_z:
            height of the last instance of positive buoyancy below the el

    Returns:
        psi:
            Parameter defined in eqn. 52, constant for a given equilibrium level, see COMPUTE_ECAPE.m L88 (pitchfork)
    """

    # additional constants as denoted in section 4 step 1.
    sigma = 1.6 * units("dimensionless")
    alpha = 0.8 * units("dimensionless")
    l_mix = 120.0 * units("m")
    pr = (1.0 / 3.0) * units("dimensionless")  # prandtl number
    ksq = 0.18 * units("dimensionless")  # von karman constant

    psi = (ksq * alpha**2 * np.pi**2 * l_mix) / (4.0 * pr * sigma**2 * el_z)

    return psi
```

However, in Peters et. al. 2023 Eq. 52 (at least the version at https://arxiv.org/pdf/2301.04712.pdf), there is no 4 in the denominator, and all other terms are present. 

![image](https://github.com/citylikeamradio/ecape/assets/114271919/58bbe3c2-d7eb-4ce6-a754-ba9cea8ff37f)

This is what I believe to be causing the large mismatch between the ECAPE value shown in the bottom left and the entrained parcel shown on the Skew-T. The storm relative inflow contribution to ECAPE-A is not enough to explain this mismatch, as it should only be about 135 J kg^-1.

![RAOB_Chanhassen-MN_20230719-21](https://github.com/citylikeamradio/ecape/assets/114271919/1800f8ef-aa27-48fd-88da-14498e1161f7)

Without removing the 4 from the denominator, `psi` is calculated to be `0.0024273940501859416 dimensionless`. After removing it, it is calculated to be `0.009709576200743766 dimensionless`.

After removing the 4, the plotted entraining parcel path appears to much more closely match the ECAPE value given by this library's code.

![RAOB_Chanhassen-MN_20230719-21](https://github.com/citylikeamradio/ecape/assets/114271919/13e7cb86-4e8b-4411-8a95-0413e73ae5d3)

**Comment by citylikeamradio** [comment]
Thanks for the detailed report!

My suspicion is that the coefficient was in the Matlab source code or preprint paper. I'll source that & fix tomorrow or this weekend.

Appreciate the work you're doing!

**Comment by a-urq** [comment]
I've looked a bit more at the paper and it says two different things in two

**Comment by a-urq** [comment]
I've looked a bit more at the paper and it says two different things in two different places. Eq. 41 does have a 4 in the denominator, and Eq. 52 has no 4, both in the preprint.

![image](https://github.com/citylikeamradio/ecape/assets/114271919/48b7ae30-d44c-4985-a845-59d02f515e99)
![image](https://github.com/citylikeamradio/ecape/assets/114271919/7d0fa253-154a-4ef1-9bd0-206de183e91e)

I've had some issues with consistency between values and parcels both with and without the 4. I'm planning to ask Dr. Peters about this and figure out what is going on here.

**Comment by a-urq** [comment]
I've looked more deeply into this issue, and every instance of Psi I can find in Dr. Peters's code has a 4 in the denominator. I believe the version without the 4 in Eq. 52 is an anomaly and the 4 should stay.
